config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :ingredient_pantries, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:show, :index] do
    resources :favorite_recipes, only: [:create]
  end

  resources :favorite_recipes, only: [:destroy]
  resources :ingredient_pantries, except: :show
  resources :recipes, only: [:show, :index]

  resources :ingredient_pantries, except: :show
  resources :recipes, only: [:show, :index]

  get "profile", to: "pages#profile"
  get "landing", to: "pages#landing"
  resources :tasks, except: [:show, :new] do
    patch "complete", to: "tasks#complete"
  end
  get "yourfavorite", to: "pages#yourfavorite"


  # resource :basket, only: [:show, :update, :destroy]

  # resolve("Basket") { route_for(:basket) }
  # end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredients_pantries
  has_many :recipes_ingredients
  validates :name, uniqueness: true
end

app/models/ingredient_pantry.rb
class IngredientPantry < ApplicationRecord
  belongs_to :user
  belongs_to :ingredient
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  validates :name, presence: true, uniqueness: true
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :ingredient_pantries
  has_many :favorite_recipes
  has_many :recipes, through: :favorite_recipes
  has_many :tasks

  has_many :favorite_recipes
  has_many :recipes, through: :favorite_recipes

  has_many :tasks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo

  validates :phone, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo, :phone])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :photo, :phone])
  end
end

app/controllers/favorite_recipes_controller.rb
class FavoriteRecipesController < ApplicationController
  def create
    @recipe = Recipe.find(params[:recipe_id])
    FavoriteRecipe.create(recipe: @recipe, user: current_user)
    redirect_to @recipe
  end

  def destroy
    @favorite = FavoriteRecipe.find(params[:id])
    @recipe = @favorite.recipe
    @favorite.destroy
    redirect_to @recipe
  end
end

app/controllers/ingredient_pantries_controller.rb
class IngredientPantriesController < ApplicationController

  def index
    @ingredients_pantries = IngredientPantry.where(user: current_user).order( best_before: :asc)
    # Semana que vem fazer um background job para verificar se está chegando os produtos na validade 1x por dia
    if params[:query].present?
      sql_query = "name ILIKE :query"
      ingredients = Ingredient.where(sql_query, query: "%#{params[:query]}%")
      @ingredients_pantries = @ingredients_pantries.where(ingredient: ingredients)
    end
    # expiring = @ingredients_pantries.reject do |ingredient|
    #   ingredient.best_before - Date.today >= 2
    # end
    # TwilioClient.new.send_text(current_user, "You have ingredients expiring in your storage!") unless expiring.empty?
    # Descomentar as linhas de cima para Twilio funcionar :)
    respond_to do |format|
      format.html { }
      format.text { render partial: "ingredient_pantries/ingredient_infos", locals: { ingredients: @ingredients_pantries }, formats: [:html] }
    end
  end

  def new
    @ingredient_pantry = IngredientPantry.new
  end

  def create
    @ingredient_pantry = IngredientPantry.new(ingredient_pantries_params)
    @ingredient_pantry.user = current_user

    if @ingredient_pantry.save
      redirect_to ingredient_pantries_path, notice: 'Ingredient was successfully created!'
    else
      render :new
    end
  end

    def destroy
      @ingredient_pantry = IngredientPantry.find(params[:id])
      @ingredient_pantry.destroy
      redirect_to ingredient_pantries_path
    end

    def update
      @ingredient_pantry = IngredientPantry.find(params[:id])
      if @ingredient_pantry.update(ingredient_pantries_params)
        redirect_to ingredient_pantries_path
      else
        render :edit
      end
    end

    def edit
      @ingredient_pantry = IngredientPantry.find(params[:id])
    end

    private

  def ingredient_pantries_params
    params.require(:ingredient_pantry).permit(:ingredient_id, :best_before, :lot, :quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :landing ]

  def home
    if current_user
     @name = current_user.name.split(" ")
    end
  end

  def landing
  end

  def profile
  end

  def yourfavorite
    @recipes = current_user.recipes
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all

    if params[:query].present?
      sql_query = "name ILIKE :query"
      @recipes = Recipe.where(sql_query, query: "%#{params[:query]}%")
    end
    respond_to do |format|
      format.html { }
      format.text { render partial: "recipes/recipe_infos", locals: { recipes: @recipes }, formats: [:html] }
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: %i[index create complete]

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.user = current_user
    task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def complete
    @task = Task.find(params[:task_id])
    @task.completed = !@task.completed
    @task.save
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ingredient_pantries/_ingredient_infos.html.erb
<div class="container-products" data-search-target="list">
  <% ingredients.each_with_index do |ingredient, index| %>
    <div class= "card-product" id=<%='card-product-margin' if ingredients.length - 1 == index %>>
      <% if ingredient.ingredient.image_url.present? %>
        <%= image_tag(ingredient.ingredient.image_url) %>
      <% else %>
        <img src="https://spoonacular.com/recipeImages/73420-312x231.jpg", class="picture mt-3"/>
      <% end %>
      <div class="card-product-infos">
        <h2><%=ingredient.ingredient.name %></h2>
        <p class=<%='best-before' if ingredient.best_before - Date.today <= 2 %>><%=ingredient.best_before %></p>
        <p>Quantity: <strong><%=ingredient.quantity %></strong></p>
      </div>
      <div class="product-card-links">
        <%= link_to edit_ingredient_pantry_path(ingredient) do %>
          <i class="fas fa-edit icon-medium"></i>
        <% end %>
        <%= link_to ingredient_pantry_path(ingredient), method: :delete do %>
          <i class="fas fa-trash icon-medium"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/ingredient_pantries/edit.html.erb
<%# div class="container-pantry" %>
<div class="background-home">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="form-pantry">
        <h2><strong>Add An Ingredient :</strong></h2>
        <%= simple_form_for @ingredient_pantry, html: { class: "letter-h3" }  do |f| %>
          <%= f.input :best_before %>
          <%= f.input :lot %>
          <%= f.input :quantity %>
          <%= f.association :ingredient %>
          <%= f.submit class: 'btn btn-warning w-100' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ingredient_pantries/index.html.erb
<div data-controller="search" class="pt-5">

  <%= form_tag  ingredient_pantries_path, method: :get, class: "simple_form search css-form", data: { search_target: "form" } do %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
        params[:query],
        class: "form-control string required",
        placeholder: "Find an Ingredient",
        data: { search_target: "input", action: "input->search#update" }
      %>
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>

  <div class="background-logo">
    <h1 class= "mt-3"> Your Ingredients</h1>
  </div>
  <div class="list-user-ingredients mb-5">
    <div class="cards-margim">
      <%= render "ingredient_infos", ingredients: @ingredients_pantries %>
    </div>
</div>
<%# <div class="card-trip">
  <img src="https://images.pexels.com/photos/3673762/pexels-photo-3673762.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" />
  <div class="card-trip-infos">
    <div>
      <h2>Title here</h2>
      <p>Short description here!</p>
    </div>
  </div>
</div> %>

app/views/ingredient_pantries/new.html.erb
<%# div class="container-pantry" %>
<div class="background-home">
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="form-pantry">
        <h2><strong>Add An Ingredient :</strong></h2>
        <%= simple_form_for [@ingredient_pantry], html: { class: "letter-h3" }  do |f| %>
          <%= f.input :best_before %>
          <%= f.input :lot %>
          <%= f.input :quantity %>
          <%= f.association :ingredient, input_html: { class: 'select2', data: {controller: "select2"}} %>
          <%= f.submit class: 'btn btn-warning w-100' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZeroWaste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' if action_name == "home" %>

    <%= render 'shared/navbar' unless action_name == "home" || action_name == "landing" %>

  </body>
</html>

app/views/pages/_welcome.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
<meta charset="UTF-8"/>
<title>Zero Waste</title>
</head>

<body>
<div class="container">
  <h1>Zero Waste </h1>
<div class="text-center mt-5 mb-5">
  <h1><strong>text</strong></h1>
    <%= %>
</div>

</body>

</html>

<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home.html.erb
<div class="background-home">
  <div class="background-logo">
    <%= image_tag "logozw.png", width: 200, height: 60, class: "image-logo mt-2" %>
  </div>
  <div class="container-grid">
    <div class="text-center margin-home">
    <% if current_user %>
      <h5><strong>Hello, <%= @name[0] %>!</strong></h5>
    <% else %>
      <h5><strong>Welcome!</strong></h5>
    <% end %>
    </div>
    <div class="container home-grid">
      <% if current_user%>
        <%= link_to profile_path, class: "link-home" do %>
          <div class="home-card">
            <i class="fas fa-user icon-big"></i>
            <p class="mt-2">Profile</p>
          </div>
         <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "link-home" do %>
          <div class="home-card">
            <i class="fas fa-user icon-big"></i>
            <p class="mt-2">Login</p>
          </div>
         <% end %>
       <% end %>

      <%= link_to new_ingredient_pantry_path, class: "link-home" do %>
        <div class="home-card">
          <i class="fas fa-plus icon-big mt-1"></i>
          <p class="mt-2">Add New Ingredient</p>
        </div>
      <% end %>

      <%= link_to yourfavorite_path, class: "link-home" do %>
        <div class="home-card">
          <i class="fas fa-heart icon-big"></i>
          <p class="mt-2">My Favorites</p>
        </div>
      <% end %>

      <%= link_to ingredient_pantries_path, class: "link-home" do %>
        <div class="home-card">
          <i class="fas fa-clipboard-list icon-big"></i>
          <p class="mt-2">My Pantry</p>
        </div>
      <% end %>

      <%= link_to recipes_path, class: "link-home" do %>
        <div class="home-card">
          <i class="fas fa-book icon-big"></i>
          <p class="mt-2">Recipes</p>
        </div>
      <% end %>

      <%= link_to tasks_path, class: "link-home" do %>
        <div class="home-card">
          <i class="fas fa-list icon-big"></i>
          <p class="mt-2">Checklist</p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/landing.html.erb
<%= link_to root_path do %>
  <div class="background-landing">
    <%=image_tag("zw.gif") %>
  </div>
<% end %>

app/views/pages/profile.html.erb
<div class="profile py-4">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-4">
        <div class="card shadow-sm">
          <div class="card-header bg-transparent text-center mb-2">
            <h3>Edit profile</h3>
            <% if current_user.photo.key %>
              <%= cl_image_tag current_user.photo.key, height: 250, width: 250, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://www.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <div class="card shadow-sm">
          <div class="card-header bg-transparent border-0">
            <h3 class="mb-3 mt-3"><i class="far fa-clone pr-1"></i>General Information</h3>
          </div>
          <div class="card-body pt-0">
            <table class="table table-bordered">
              <tr>
                <th width="30%">Name</th>
                <td width="2%">:</td>
                <td><%= current_user.name %></td>
              </tr>
              <tr>
                <th width="30%">email</th>
                <td width="2%">:</td>
                <td><%= current_user.email %></td>
              </tr>
              <tr>
                <th width="30%">phone number</th>
                <td width="2%">:</td>
                <td><%= current_user.phone %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/yourfavorite.html.erb
<div class="background-home">
  <div class="profile py-4">
    <div class="background-logo-favorite">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-4">
            <div class="card shadow-sm mb-5">
              <div class="card-header bg-transparent text-center mt-2">
                <h3>My Favorites</h3>
              </div>
              <%= render @recipes %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<%= link_to recipe_path(recipe) do %>
  <div class="card-trip mt-3">
    <% if recipe.url_image.present? %>
      <%= image_tag(recipe.url_image) %>
    <% else %>
      <img src="https://spoonacular.com/recipeImages/73420-312x231.jpg", class="picture mt-3"/>
    <% end %>
    <div class="card-trip-infos">
      <div class="infos">
        <p><%= recipe.name%></p>
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipe_infos.html.erb
<div class="cards-margim" data-search-target="list">
  <% recipes.each do |recipe|%>
    <%= render "recipe", recipe: recipe %>
  <% end %>
</div>

app/views/recipes/index.html.erb
<div data-controller="search">
  <div class="fixed-search">
    <%= form_tag recipes_path, method: :get, class: "simple_form search", data: { search_target: "form" } do %>
      <div class="search-form-control form-group">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control string required",
          placeholder: "Find a Recipe",
          data: { search_target: "input", action: "input->search#update" }
        %>
        <button name="button" type="submit" class="btn btn-flat">
          <i class="fas fa-search"></i> Search
        </button>
      </div>
    <% end %>
  </div>
  <div class="background-home">
    <div class="margin-recipe">
      <%= render "recipe_infos", recipes: @recipes %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="background-home">
  <div class="card-trip">
    <% if @recipe.url_image.present? %>
      <%= image_tag(@recipe.url_image) %>
    <% else %>
      <img src="https://spoonacular.com/recipeImages/73420-312x231.jpg", class="picture mt-3"/>
    <% end %>
    <div class="card-trip-infos">
      <div>
        <div class="d-flex justify-content-between">
          <h2>Recipe</h2>
            <% if current_user.recipes.where(id: @recipe.id).present?%>
              <%= link_to favorite_recipe_path(current_user.favorite_recipes.find_by(recipe: @recipe)), method: :delete, remote: true do %>
                <i class="fas fa-heart icon-big"></i>
              <% end %>
            <% else %>
              <%= link_to recipe_favorite_recipes_path(@recipe), method: :post, remote: true do %>
                <i class="far fa-heart"></i>
              <% end %>
            <% end %>
        </div>
        <div class="cards-margim">
          <div class="card-trip-center">
            <div class="card-trip-infos-center mt-4">
            <div class="text-start">
              <div class="infos" text>
                <p><%= @recipe.name%></p>
                <p><%= @recipe.description.html_safe%></p>
              </div>
            </div>
              <div>
                <a class="btn btn-ghost mt-4" href=<%=@recipe.spoon_url%> target=”_blank”>Go to Recipe</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%#= image_tag "#", width: 50, class: "mt-2" %>
  <div class="footer-copyright">
    Zero Waste
  </div>
  <div>
    This project was built by women <i class="fas fa-heart"></i>
  </div>
  <div class="footer-links">
    <a href="https://www.linkedin.com/in/akemi-hiruma" target=”_blank”><i class="fab fa-linkedin"></i></a>
    <a href="https://www.linkedin.com/in/bruna-suzuki-a430bb238" target=”_blank”><i class="fab fa-linkedin"></i></a>
    <a href="https://www.linkedin.com/in/erica-hery-park" target=”_blank”><i class="fab fa-linkedin"></i></a>
    <a href="https://www.linkedin.com/in/natalialimaa" target=”_blank”><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-zerowaste">
      <ul class="navbar-links">
        <%= link_to root_path do %>
          <li class="navbar-item">
            <i class="fas fa-home"></i>
            <p>Home</p>
          </li>
        <% end %>

       <%= link_to new_ingredient_pantry_path do %>
          <li class="navbar-item">
            <i class="fas fa-plus"></i>
              <p>Add</p>
          </li>
        <% end %>

         <%= link_to recipes_path do %>
          <li class="navbar-item">
            <i class="far fa-file-alt"></i>
                <p>Recipe</p>
          </li>
        <% end %>

         <%= link_to ingredient_pantries_path do %>
          <li class="navbar-item">
           <i class="fas fa-apple-alt"></i>
             <p>My Pantry</p>
          </li>
        <% end %>

      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <li class="navbar-item">
            <i class="fas fa-user-alt-slash"></i>
            <p>Logout</p>
          </li>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path do %>
          <li class="navbar-item">
            <i class="fas fa-user"></i>
            <p>Login</p>
          </li>
        <% end %>
      <% end %>
      </ul>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <div class="container">
    <div class="search-form-control form-group">
      <%= f.input :title, label: false, wrapper: false, placeholder: "New Task", class: "search-description" %>
      <button name="button" type="submit" class="btn btn-flat me-3">
        <i class="far fa-edit"></i> Edit
      </button>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="background-home">
  <div class="background-logo-edit">
    <div class="container">
      <div class="card-checklist-edit">
        <div class="justify-content-center mb-5">
          <h2 class="text-center">Edit task</h2>
          <%= render 'form', task: @task %>
          <%= link_to tasks_path do %>
            <i class="fa fa-history"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="background-home">

    <div class="container">
      <div class="card-checklist">
        <div class="justify-content-center mb-5">
          <%= simple_form_for @task, remote: true, html: { class: "search" } do |f| %>
            <div class="search-form-control form-group">
              <%= f.input :title, label: false, wrapper: false, placeholder: "New Task", class: "search-description" %>
              <button name="button" type="submit" class="btn btn-flat">
                <i class="fas fa-plus"></i> Add
              </button>
            </div>
          <% end %>

          <ul id="tasks">
            <% @tasks.each do |task| %>
              <li>
                <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.title}?" } do %>
                  <i class="far fa-trash-alt"></i>
                <%= link_to task_complete_path(task), method: :patch, remote: true do %>
                  <% if task.completed %>
                    <i class="far fa-check-square"></i>
                  <% else %>
                    <i class="far fa-square"></i>
                  <% end %>
                <% end %>
                <%= link_to task.title, edit_task_path(task) %>

                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

</div>